services:

  django:
    image: document-ai-image
    build: .
    container_name: document_ai_api

    working_dir: /app

    env_file:
      - .env

    volumes:
      - .:/app
      - paddle_models:/root/.paddlex
      - paddleocr_models:/root/.paddleocr

    ports:
      - "8000:8000"

    command:
      python manage.py runserver 0.0.0.0:8000

    depends_on:
      - redis


  celery:
    image: document-ai-image
    build: .
    container_name: document_ai_celery

    working_dir: /app

    env_file:
      - .env

    volumes:
      - .:/app
      - paddle_models:/root/.paddlex
      - paddleocr_models:/root/.paddleocr

    command:
      celery -A config worker --loglevel=info

    depends_on:
      - redis


  redis:
    image: redis:7
    container_name: document_ai_redis


volumes:

  paddle_models:

  paddleocr_models: